BOT_TOKEN='7112931136:AAFfwPwWK_EKrRX1VdeTDajWxCNf5HV0JhI'
OPENAI_API_BASE='http://localhost:1234/v1/'
OPENAI_API_KEY='lm-studio'
LLM_MODEL='bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF'
MAX_TOKENS='1024'
BOT_WRITE_TIMEOUT='480'
BOT_TEMPERATURE='0.5'
HISTORY_DIR='C:/Projects/vscode-basics/GoIT-Python-Data-Science/MyProjects/TelegramAIChatbot/code/conversations/'
