BOT_TOKEN='YOU_BOT_TOKEN'
OPENAI_API_BASE='http://localhost:1234/v1/'
OPENAI_API_KEY='lm-studio'
LLM_MODEL='lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF'
MAX_TOKENS='1024'
BOT_WRITE_TIMEOUT='480'
BOT_TEMPERATURE='0.5'
HISTORY_DIR='C:/Projects/vscode-basics/GoIT-Python-Data-Science/MyProjects/TelegramAIChatbot/code/conversations/'
